# Generated by Django 5.2.6 on 2025-10-10 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='conference',
            name='Description',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(30, 'La description doit contenir au moins 30 caractères.')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Le nom de la conférence ne doit contenir que des lettres.', regex='^[A-Za-zÀ-ÿ\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='theme',
            field=models.CharField(choices=[('cs&ia', 'Computer Science & IA'), ('cs', 'Social Science'), ('SE', 'Science and Engineering')], max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(help_text='Le fichier doit être au format PDF uniquement.', upload_to='paper/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
