# Generated by Django 5.2.6 on 2025-10-13 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0002_rename_user_id_submission_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="L'identifiant de la soumission doit être un nombre.", regex='^\\d+$')]),
        ),
    ]
