# Generated by Django 5.2.6 on 2025-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0003_alter_submission_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
